global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: bentoml_api
    metrics_path: /metrics
    static_configs:
      - targets: ["api:3000"]

  - job_name: airflow_statsd
    static_configs:
      - targets: ["statsd-exporter:9102"]

  - job_name: postgres_mlflow
    static_configs:
      - targets: ["postgres-exporter-mlflow:9187"]

  - job_name: postgres_airflow
    static_configs:
      - targets: ["postgres-exporter-airflow:9187"]

  - job_name: minio
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ["minio:9000"]

  - job_name: node
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: pushgateway
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]
